### ISSUE TITLE
remove references to lightblue

### ISSUE THREAD

**Issue by ktdreyer** [redhat-exd-rebuilds/freshmaker#49]
There are a couple of references to Lightblue, but Pyxis is replacing Lightblue. Can we drop all the Lightblue references and code?

**Comment by qixiang** [comment]
LightBlue is still used, Pyxis is used in a new handler for rebuilding bundle images, migrating to Pyxis is planned, I'll leave this open and close it once the migration is done.

**Comment by qixiang** [comment]
Freshmaker now uses Pyxis for all metadata queries, LightBlue is decommissioned, closing this.
