### ISSUE TITLE
Has freshmaker been retired from Fedora?

### ISSUE THREAD

**Issue by Cav4ever** [redhat-exd-rebuilds/freshmaker#80]
@qixiang 
Hi Qixiang:
I can not find the higher fedora release than fedora30 for freshmaker in [fedora koji](https://koji.fedoraproject.org/koji/packageinfo?packageID=24422).
And I find that freshmaker has been retired from Fedora in [fedora dist-git](https://src.fedoraproject.org/rpms/freshmaker).
The newest tag of Freshmaker in github is v0.1.2 which was released on 21 May 2018, but the code is still updated in github.
So, I want to know:
1, How can I install freshmake on fedora31 or higer fedora release?
2, Has freshmaker been retired from Fedora? If yes, what service or software is uesd to replace freshmaker?

**Comment by qixiang** [comment]
Hi @Cav4ever:

> 1, How can I install freshmake on fedora31 or higer fedora release?
> 2, Has freshmaker been retired from Fedora? If yes, what service or software is uesd to replace freshmaker?

We retired Freshamaker in Fedora a while ago because the plan of using Freshmaker in Fedora has been changed, so we don't do packaging for it anymore. Freshmaker was never used by Fedora infra at all, so I think there is no service for replacing Freshmaker, but there could be some services that are responsible for rebuilding particular artifacts, I'm not sure about this.

You can still find the latest code of Freshmaker on github, and run it in container, however it's designed to work with several Red Hat internal services, so I doubt it can work for your purpose.

**Comment by Cav4ever** [comment]
@qixiang
Hi Qixiang:
Thank you for your quick reply.

> so I think there is no service for replacing Freshmaker, but there could be some services that are responsible for rebuilding particular artifacts, I'm not sure about this.

I need the functions from freshmaker on fedora31 or higer release.
So, I wonder what service or software can complete the work of freshmaker.
But, I cannot find any useful information by lookup "freshmaker" or "freshmaker fedora31" by google.
Would you please give me some information about where can I find "what service or software can complete the work of freshmaker"?

**Comment by qixiang** [comment]
Hi @Cav4ever ,

It depends what functionality you're looking for, the main functionality Freshmaker provides is rebuilding container images when there are some updates for rpms in container images. Take Fedora infrastructure as an example, the rpms updates are shipped via bodhi (https://bodhi.fedoraproject.org), with updates info from bodhi, you can try to figure out which container images are impacted by the updates and then rebuild the container images via koji (https://koji.fedoraproject.org/koji/). Freshmaker automates a similar workflow along with several other services.

**Comment by Cav4ever** [comment]
@qixiang
Hi Qixiang:

The situation I want to use freshmaker is in MBS(Module Build Service).
[Freshmaker SOP](https://fedora-infra-docs.readthedocs.io/en/latest/sysadmin-guide/sops/freshmaker.html) describes the application of freshmaker in MBS.
So, what service or software can complete the work of freshmaker for MBS?

**Comment by qixiang** [comment]
> The situation I want to use freshmaker is in MBS(Module Build Service).
> [Freshmaker SOP](https://fedora-infra-docs.readthedocs.io/en/latest/sysadmin-guide/sops/freshmaker.html) describes the application of freshmaker in MBS.
> So, what service or software can complete the work of freshmaker for MBS?

Ah, Freshmaker dropped the feature of rebuilding modules a long time ago, it only supports rebuilding container images and operator bundles now, I'm not sure whether there is any tool or service exist for rebuilding modules.

**Comment by Cav4ever** [comment]
@qixiang
Hi Qixiang:

Would you please give me some information about where can I find "what service or software can complete the work of freshmaker for MBS"?
Maybe some other committers' or maintainers' Email adderess I can ask for assist.
Any suggestion is appreciated.

**Comment by qixiang** [comment]
@Cav4ever sorry, I don't know if there is any service/software exists for this purpose, so I have no suggestion on this.

**Comment by Cav4ever** [comment]
> @Cav4ever sorry, I don't know if there is any service/software exists for this purpose, so I have no suggestion on this.

Thank you for your quick reply and kind help.

**Comment by qixiang** [comment]
@Cav4ever btw, I believe you already know that MBS is a service for building modules (but not for rebuilding modules for rpm updates), in case you don't know this, you can check:
- https://pagure.io/fm-orchestrator/
- https://docs.fedoraproject.org/en-US/modularity/

**Comment by Cav4ever** [comment]
@qixiang
Yes, I know that MBS is a service for building modules.
And from [Freshmaker SOP](https://fedora-infra-docs.readthedocs.io/en/latest/sysadmin-guide/sops/freshmaker.html), I know freshmaker can trigger rebuilds for MBS.
> Module Builds
> When a spec file changes on a particular dist-git branch, trigger rebuilds of all modules that declare dependencies on that rpm branch.
> Freshmaker deals with this by watching the bus for dist-git fedmsg messages. When it sees a change on a branch, it looks up the list of modules that depend on that branch, and requests rebuilds of them in the MBS.

So, I am trying to find "what service or software can complete the work of freshmaker for MBS on fedora31 or higer release".
