### ISSUE TITLE
How to deploy freshmaker for MBS on fedora28

### ISSUE THREAD

**Issue by Cav4ever** [redhat-exd-rebuilds/freshmaker#81]
@qixiang
Hi Qixiang:

I need to deploy freshmaker for MBS on fedora28.
The version of freshmaker  on my fedora28 is freshmaker-0.0.4-5.fc28.noarch.(through dnf install -y freshmaker)
I have the following doubts about the deploying of freshmaker for MBS on fedora28.

1. Can I deploy freshmaker on a independent server(neither MBS server nor distgit server )?
2. Is “/etc/freshmaker/config.py” the only file I need to modify according to my envrionment(GIT_BASE_URL, MBS_BASE_URL,,,)?
3. I am not really understand the meaning and function of PDC_URL in config.py. Do I need my own PDC？
4. The [docs about freshmaker](https://redhat-exd-rebuilds.github.io/freshmaker/) is not for freshmaker-0.0.4. Would you please give me some information that can help me to modify config.py and deploy freshmaker for MBS on fedora28?

**Comment by qixiang** [comment]
Hi @Cav4ever , as I mentioned in #80 Freshmaker dropped the plan of supporting rebuilding modules a long time ago, so it was just on the initial plan and  we have never reached that goal.

**Comment by Cav4ever** [comment]
Thank you for your quick reply and kind help.
