### ISSUE TITLE
what is a Freshmaker "build_id"?

### ISSUE THREAD

**Issue by ktdreyer** [redhat-exd-rebuilds/freshmaker#99]
The [API v1 documentation](https://docs.pagure.org/freshmaker/api_v1.html#artifact-build-json-representation) does not tell users what `build_id` is.

For containers, it looks like `build_id` is actually the Koji buildContainer *task* ID, not a Koji build ID. This is an important gotcha.

`freshmaker/handlers/koji/rebuild_images_on_parent_image_build.py` has a hint about this:

```python
# build_id is actually task id in build system, find out the actual build first
```

The problem is that `freshmaker/models.py` has this comment for `build_id`:

```python
# Id of corresponding real build in external build system. Currently, it
# could be ID of a build in MBS or Koji, maybe others in the future.
# build_id may be NULL, which means this build has not been built in
# external build system.
```

The line `build_id may be NULL, which means this build has not been built in external build system.` is ambiguous.

Do we populate `build_id` when the Koji buildContainer task fails?

- If so, let's update this comment to reflect this.
- If not, let's update this comment from `built` to `built successfully`.

And let's update `docs/api_v1.rst` to describe how `build_id` relates to a Koji buildContainer task ID

(Longer term, it would be great to use the name "task_id" or "koji_task_id" throughout the codebase instead of re-using the name "build_id" to have two different meanings).

**Comment by qixiang** [comment]
> The [API v1 documentation](https://docs.pagure.org/freshmaker/api_v1.html#artifact-build-json-representation) does not tell users what `build_id` is.
> 
> For containers, it looks like `build_id` is actually the Koji buildContainer _task_ ID, not a Koji build ID. This is an important gotcha.

Yes, it's koji/brew task id for container images, freshmaker was designed to support different builds (modules, images) at the beginning, so it was named `build_id` (iirc, MBS calls it module builds instead of tasks), however the other requirements were dropped and only supports container image builds at this moment.

> 
> `freshmaker/handlers/koji/rebuild_images_on_parent_image_build.py` has a hint about this:
> 
> ```python
> # build_id is actually task id in build system, find out the actual build first
> ```
> 
> The problem is that `freshmaker/models.py` has this comment for `build_id`:
> 
> ```python
> # Id of corresponding real build in external build system. Currently, it
> # could be ID of a build in MBS or Koji, maybe others in the future.
> # build_id may be NULL, which means this build has not been built in
> # external build system.
> ```
> 
> The line `build_id may be NULL, which means this build has not been built in external build system.` is ambiguous.

Yes, this comment is incorrect, it's always task id instead of build id.

> 
> Do we populate `build_id` when the Koji buildContainer task fails?
>

Yes, it's populated when a **task** is submitted successfully.
 
> * If so, let's update this comment to reflect this.
> * If not, let's update this comment from `built` to `built successfully`.
> 
> And let's update `docs/api_v1.rst` to describe how `build_id` relates to a Koji buildContainer task ID
> 

Sure, I'll update this later.

> (Longer term, it would be great to use the name "task_id" or "koji_task_id" throughout the codebase instead of re-using the name "build_id" to have two different meanings).

There are other services may check the `build_id`, it's not easy to rename this, though we can rename it in codebase but keep the name in API.

**Comment by ktdreyer** [comment]
Thank you for explaining this.

Does Freshmaker populate it's `build_id` when it *submits* a buildContainer task successfully, or when Koji *completes* the buildContainer task? In other words, what can users expect when they see `build_id` is not null?

Regarding renaming the `build_id` references: I understand other services rely on this field, and it would be an API-breaking change, so I don't think this is worth it today.

At this point, just documenting all these details in the API docs would go a long way to reducing confusion.

Does Freshmaker interact with MBS any more?

**Comment by qixiang** [comment]
> Thank you for explaining this.
> 
> Does Freshmaker populate it's `build_id` when it _submits_ a buildContainer task successfully, or when Koji _completes_ the buildContainer task? In other words, what can users expect when they see `build_id` is not null?
> 

`build_id` is populated when task is submitted, as soon as the task id is available, that task can be canceled, can failed later and thus no build will be available.

> Regarding renaming the `build_id` references: I understand other services rely on this field, and it would be an API-breaking change, so I don't think this is worth it today.
> 
> At this point, just documenting all these details in the API docs would go a long way to reducing confusion.

Agree. 

> 
> Does Freshmaker interact with MBS any more? EDIT: Re-reading old GitHub issues, I see it does not support it any more. I guess there is a lot more code to drop now.

Yes, it does not interact with MBS anymore, some can be dropped, and some need to be kept, for example, there is database record that still refer to the MBS event types and so on.

**Comment by qixiang** [comment]
Update doc and comment for `build_id` in #100 
And internal card CLOUDWF-6150 is filed for reviewing and cleanup the codebase.

**Comment by ktdreyer** [comment]
With those doc PRs, I consider this GitHub issue resolved now, so you can close this.

**Comment by qixiang** [comment]
Thanks, closing.
